### ISSUE TITLE
Use gss-utils

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/HMRC_Trade#1]
Start with landing page, scrape to discover metadata, output metadata and schema.

**Comment by mikeAdamss** [comment]
@ajtucker can you bulk this out a bit for me when you get a chance please (slack is fine, you're in meetings today is all 😄).

I can see we're currently getting some metadata, needs a better idea of what we're missing and where to put it. Can't dovetail the fields in the manual /metadata field with anything I can see in the scraper.

**Comment by mikeAdamss** [comment]
done.
